// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platform is not supported for this app.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS platform is not configured for this app.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS platform is not configured for this app.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows platform is not configured for this app.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux platform is not configured for this app.',
        );
      default:
        throw UnsupportedError(
          'Unknown platform: ${defaultTargetPlatform}',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmY_fv-YVSjAUAzIMlt5V4Hi00kpOJS9o',
    appId: '1:1077308768674:android:fd5741525f719a388bf2fb',
    messagingSenderId: '1077308768674',
    projectId: 'see-you-in-ceu-e5dcd',
    storageBucket: 'see-you-in-ceu-e5dcd.firebasestorage.app',
  );
} 